name: Attend

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth python-dotenv

      - name: Run script
        id: run-script
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: |
          python scripts/main.py 2>&1 | tee output.log
        continue-on-error: true

      - name: Check for token expiration error
        id: check-errors
        run: |
          if grep -q "invalid_grant: Token has been expired or revoked" output.log; then
            echo "Error found"
            echo "error=true" >> $GITHUB_ENV
          else
            echo "No error found"
            echo "error=false" >> $GITHUB_ENV
          fi

      - name: Commit error log if there are errors
        if: env.error == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add readme.md
          git commit -m "Update readme.md with error log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
