name: Update Attendance

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth python-dotenv

      - name: Run script
        env:
          CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
