name: Attend

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth python-dotenv

      - name: Run script
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python scripts/main.py
